config/routes.rb
Teamawesome::Application.routes.draw do
  resources :user_stories

  resources :stories

  root 'static_pages#home'                                           
  get "static_pages/new_user"
  get "static_pages/voting"
  get "static_pages/accounts"
  get "static_pages/about"
  get "static_pages/contactus"
  resources :microposts

  resources :users

end

app/models/user_story.rb
class UserStory < ActiveRecord::Base
end

app/controllers/user_stories_controller.rb
class UserStoriesController < ApplicationController
  before_action :set_user_story, only: [:show, :edit, :update, :destroy]

  # GET /user_stories
  # GET /user_stories.json
  def index
    @user_stories = UserStory.all
  end

  # GET /user_stories/1
  # GET /user_stories/1.json
  def show
  end

  # GET /user_stories/new
  def new
    @user_story = UserStory.new
  end

  # GET /user_stories/1/edit
  def edit
  end

  # POST /user_stories
  # POST /user_stories.json
  def create
    @user_story = UserStory.new(user_story_params)

    respond_to do |format|
      if @user_story.save
        format.html { redirect_to @user_story, notice: 'User story was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_story }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_stories/1
  # PATCH/PUT /user_stories/1.json
  def update
    respond_to do |format|
      if @user_story.update(user_story_params)
        format.html { redirect_to @user_story, notice: 'User story was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_stories/1
  # DELETE /user_stories/1.json
  def destroy
    @user_story.destroy
    respond_to do |format|
      format.html { redirect_to user_stories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_story
      @user_story = UserStory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_story_params
      params.require(:user_story).permit(:user_id, :story_id)
    end
end

app/helpers/user_sto_ries_helper.rb
module UserStoRiesHelper
end

app/views/user_stories/_form.html.erb
<%= form_for(@user_story) do |f| %>
  <% if @user_story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_story.errors.count, "error") %> prohibited this user_story from being saved:</h2>

      <ul>
      <% @user_story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :story_id %><br>
    <%= f.number_field :story_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_stories/edit.html.erb
<h1>Editing user_story</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_story %> |
<%= link_to 'Back', user_stories_path %>

app/views/user_stories/index.html.erb
<h1>Listing user_stories</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Story</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_stories.each do |user_story| %>
      <tr>
        <td><%= user_story.user_id %></td>
        <td><%= user_story.story_id %></td>
        <td><%= link_to 'Show', user_story %></td>
        <td><%= link_to 'Edit', edit_user_story_path(user_story) %></td>
        <td><%= link_to 'Destroy', user_story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User story', new_user_story_path %>

app/views/user_stories/new.html.erb
<h1>New user_story</h1>

<%= render 'form' %>

<%= link_to 'Back', user_stories_path %>

app/views/user_stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_story.user_id %>
</p>

<p>
  <strong>Story:</strong>
  <%= @user_story.story_id %>
</p>

<%= link_to 'Edit', edit_user_story_path(@user_story) %> |
<%= link_to 'Back', user_stories_path %>