config/routes.rb
Teamawesome::Application.routes.draw do
  resources :user_stories

  resources :stories

  root 'static_pages#home'                                           
  get "static_pages/new_user"
  get "static_pages/voting"
  get "static_pages/accounts"
  get "static_pages/about"
  get "static_pages/contactus"
  resources :microposts

  resources :users

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
   validates :story, :sent1, :sent2, :sent3, :sent4, :sent5, :sent6, :sent7, :sent8, :sent9, :sent10, :sent11, :sent12, :presence => true
   validates :sent1, :length => {:maximum => 255}
   validates :sent2, :length => {:maximum => 255}
   validates :sent3, :length => {:maximum => 255}
   validates :sent4, :length => {:maximum => 255}
   validates :sent5, :length => {:maximum => 255}
   validates :sent6, :length => {:maximum => 255}
   validates :sent7, :length => {:maximum => 255}
   validates :sent8, :length => {:maximum => 255}
   validates :sent9, :length => {:maximum => 255}
   validates :sent10, :length => {:maximum => 255}
   validates :sent11, :length => {:maximum => 255}
   validates :sent12, :length => {:maximum=> 255}
   belongs_to :user
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render action: 'show', status: :created, location: @micropost }
      else
        format.html { render action: 'new' }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:STORY, :sent1, :sent2, :sent3, :sent4, :sent5, :sent6, :sent7, :sent8, :sent9, :sent10, :sent11, :sent12)
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :STORY %><br>
    <%= f.text_field :STORY %>
  </div>
  <div class="field">
    <%= f.label :sent1 %><br>
    <%= f.text_field :sent1 %>
  </div>
  <div class="field">
    <%= f.label :sent2 %><br>
    <%= f.text_field :sent2 %>
  </div>
  <div class="field">
    <%= f.label :sent3 %><br>
    <%= f.text_field :sent3 %>
  </div>
  <div class="field">
    <%= f.label :sent4 %><br>
    <%= f.text_field :sent4 %>
  </div>
  <div class="field">
    <%= f.label :sent5 %><br>
    <%= f.text_field :sent5 %>
  </div>
  <div class="field">
    <%= f.label :sent6 %><br>
    <%= f.text_field :sent6 %>
  </div>
  <div class="field">
    <%= f.label :sent7 %><br>
    <%= f.text_field :sent7 %>
  </div>
  <div class="field">
    <%= f.label :sent8 %><br>
    <%= f.text_field :sent8 %>
  </div>
  <div class="field">
    <%= f.label :sent9 %><br>
    <%= f.text_field :sent9 %>
  </div>
  <div class="field">
    <%= f.label :sent10 %><br>
    <%= f.text_field :sent10 %>
  </div>
  <div class="field">
    <%= f.label :sent11 %><br>
    <%= f.text_field :sent11 %>
  </div>
  <div class="field">
    <%= f.label :sent12 %><br>
    <%= f.text_field :sent12 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<table>
  <thead>
    <tr>
      <th>Story</th>
      <th>Sent1</th>
      <th>Sent2</th>
      <th>Sent3</th>
      <th>Sent4</th>
      <th>Sent5</th>
      <th>Sent6</th>
      <th>Sent7</th>
      <th>Sent8</th>
      <th>Sent9</th>
      <th>Sent10</th>
      <th>Sent11</th>
      <th>Sent12</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.STORY %></td>
        <td><%= micropost.sent1 %></td>
        <td><%= micropost.sent2 %></td>
        <td><%= micropost.sent3 %></td>
        <td><%= micropost.sent4 %></td>
        <td><%= micropost.sent5 %></td>
        <td><%= micropost.sent6 %></td>
        <td><%= micropost.sent7 %></td>
        <td><%= micropost.sent8 %></td>
        <td><%= micropost.sent9 %></td>
        <td><%= micropost.sent10 %></td>
        <td><%= micropost.sent11 %></td>
        <td><%= micropost.sent12 %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Story:</strong>
  <%= @micropost.STORY %>
</p>

<p>
  <strong>Sent1:</strong>
  <%= @micropost.sent1 %>
</p>

<p>
  <strong>Sent2:</strong>
  <%= @micropost.sent2 %>
</p>

<p>
  <strong>Sent3:</strong>
  <%= @micropost.sent3 %>
</p>

<p>
  <strong>Sent4:</strong>
  <%= @micropost.sent4 %>
</p>

<p>
  <strong>Sent5:</strong>
  <%= @micropost.sent5 %>
</p>

<p>
  <strong>Sent6:</strong>
  <%= @micropost.sent6 %>
</p>

<p>
  <strong>Sent7:</strong>
  <%= @micropost.sent7 %>
</p>

<p>
  <strong>Sent8:</strong>
  <%= @micropost.sent8 %>
</p>

<p>
  <strong>Sent9:</strong>
  <%= @micropost.sent9 %>
</p>

<p>
  <strong>Sent10:</strong>
  <%= @micropost.sent10 %>
</p>

<p>
  <strong>Sent11:</strong>
  <%= @micropost.sent11 %>
</p>

<p>
  <strong>Sent12:</strong>
  <%= @micropost.sent12 %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>